# Generated by Django 4.2.24 on 2025-09-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('password_change', 'Changement de mot de passe'), ('password_reset', 'Réinitialisation de mot de passe'), ('patient_created', 'Patient créé'), ('patient_updated', 'Patient modifié'), ('patient_deleted', 'Patient supprimé'), ('patient_viewed', 'Patient consulté'), ('document_uploaded', 'Document téléchargé'), ('document_processed', 'Document traité'), ('document_updated', 'Document modifié'), ('document_deleted', 'Document supprimé'), ('document_viewed', 'Document consulté'), ('document_downloaded', 'Document téléchargé'), ('report_created', 'Rapport créé'), ('report_updated', 'Rapport modifié'), ('report_deleted', 'Rapport supprimé'), ('report_viewed', 'Rapport consulté'), ('report_approved', 'Rapport approuvé'), ('report_rejected', 'Rapport rejeté'), ('user_created', 'Utilisateur créé'), ('user_updated', 'Utilisateur modifié'), ('user_deleted', 'Utilisateur supprimé'), ('user_activated', 'Utilisateur activé'), ('user_deactivated', 'Utilisateur désactivé'), ('system_backup', 'Sauvegarde système'), ('system_restore', 'Restauration système'), ('data_export', 'Export de données'), ('data_import', 'Import de données'), ('settings_updated', 'Paramètres modifiés'), ('error_occurred', 'Erreur survenue'), ('security_alert', 'Alerte de sécurité'), ('access_denied', 'Accès refusé')], max_length=50, verbose_name='Action')),
                ('description', models.TextField(verbose_name='Description')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name="ID de l'objet")),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Détails supplémentaires')),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('error', 'Erreur'), ('critical', 'Critique')], default='info', max_length=20, verbose_name='Sévérité')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='Clé de session')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Information'), ('WARNING', 'Avertissement'), ('ERROR', 'Erreur'), ('CRITICAL', 'Critique')], max_length=10, verbose_name='Niveau')),
                ('message', models.TextField(verbose_name='Message')),
                ('module', models.CharField(blank=True, max_length=100, null=True, verbose_name='Module')),
                ('function', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonction')),
                ('line_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numéro de ligne')),
                ('traceback', models.TextField(blank=True, null=True, verbose_name='Traceback')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Log système',
                'verbose_name_plural': 'Logs système',
                'ordering': ['-created_at'],
            },
        ),
    ]
